name = "cms-blog"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-04-14"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_VERSION = "22.14.0"

[env.production.vars]
NODE_VERSION = "22.14.0"
