name: Deploy to Vercel
on:
  pull_request:
    branches:
      - develop
      - master
    types: [closed]
jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Build NextJS
        run: bun run build

      # - name: Deploy to Cloudflare Pages
      #   run:
