name: Deploy to Vercel
on:
  pull_request:
    branches:
      - develop
      - master
    types: [closed]
jobs:
  deploy-vercel:
    name: SSR
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Vercel CLI
        run: bun add -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  deploy-ssr:
    name: SSR
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Build NextJS(SSR)
        run: NEXT_OUTPUT=undefined bunx @cloudflare/next-on-pages

      - name: Deploy to Cloudflare Pages
        run: bun wrangler pages deploy .vercel/output/static --project-name cms-blog

  deploy-ssg:
    name: SSG
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Build NextJS(SSG)
        run: NEXT_OUTPUT=export bun run build

      - name: Deploy to Cloudflare Pages
        run: bun wrangler pages deploy .vercel/output/static --project-name cms-blog
